-- ==========================================================
-- SISTEMA DE GESTIÓN CLÍNICA Y FARMACIA - VERSIÓN FINAL
-- PostgreSQL DDL
-- ==========================================================

-- ==========================================================
-- 1. LIMPIEZA TOTAL (OPCIONAL)
-- ==========================================================
DROP TABLE IF EXISTS inventario_semanal CASCADE;
DROP TABLE IF EXISTS inventario_mensual CASCADE;
DROP TABLE IF EXISTS detalle_salida_medicamento CASCADE;
DROP TABLE IF EXISTS salida_medicamento CASCADE;
DROP TABLE IF EXISTS detalle_entrada_medicamento CASCADE;
DROP TABLE IF EXISTS entrada_medicamento CASCADE;
DROP TABLE IF EXISTS detalle_tratamiento CASCADE;
DROP TABLE IF EXISTS tratamiento CASCADE;
DROP TABLE IF EXISTS lote_medicamento CASCADE;
DROP TABLE IF EXISTS medicamento CASCADE;
DROP TABLE IF EXISTS casa_farmaceutica CASCADE;
DROP TABLE IF EXISTS categoria_medicamento CASCADE;
DROP TABLE IF EXISTS catalogo_cie10 CASCADE;
DROP TABLE IF EXISTS diagnostico CASCADE;
DROP TABLE IF EXISTS categoria_diagnostico CASCADE;
DROP TABLE IF EXISTS examen_fisico CASCADE;
DROP TABLE IF EXISTS signo_vital CASCADE;
DROP TABLE IF EXISTS cola_atencion CASCADE;
DROP TABLE IF EXISTS consulta CASCADE;
DROP TABLE IF EXISTS medico CASCADE;
DROP TABLE IF EXISTS paciente_alergia CASCADE;
DROP TABLE IF EXISTS alergia CASCADE;
DROP TABLE IF EXISTS paciente CASCADE;
DROP TABLE IF EXISTS usuario_rol CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS parametro_farmacia CASCADE;


-- ==========================================================
-- 2. SEGURIDAD Y USUARIOS
-- ==========================================================

CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    correo VARCHAR(100) UNIQUE,
    password_hash TEXT NOT NULL,
    estado BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_rol (
    id_usuario BIGINT NOT NULL,
    id_rol BIGINT NOT NULL,
    PRIMARY KEY (id_usuario, id_rol),
    CONSTRAINT fk_ur_usuario 
        FOREIGN KEY (id_usuario) 
        REFERENCES usuario(id_usuario) 
        ON DELETE CASCADE,
    CONSTRAINT fk_ur_rol 
        FOREIGN KEY (id_rol) 
        REFERENCES rol(id_rol) 
        ON DELETE CASCADE
);


-- ==========================================================
-- 3. PACIENTES Y ATENCIÓN PREVIA
-- ==========================================================

CREATE TABLE paciente (
    id_paciente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo CHAR(1) NOT NULL,
    telefono VARCHAR(20),
    comunidad VARCHAR(150),
    antecedentes_personales_patologicos TEXT,
    antecedentes_personales_familiares TEXT,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_paciente_sexo CHECK (sexo IN ('M', 'F'))
);

CREATE TABLE alergia (
    id_alergia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE paciente_alergia (
    id_paciente BIGINT NOT NULL,
    id_alergia BIGINT NOT NULL,
    PRIMARY KEY (id_paciente, id_alergia),
    CONSTRAINT fk_paciente_alergia_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES paciente(id_paciente),
    CONSTRAINT fk_paciente_alergia_alergia
        FOREIGN KEY (id_alergia)
        REFERENCES alergia(id_alergia)
);

CREATE TABLE cola_atencion (
    id_cola BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    prioridad INT NOT NULL DEFAULT 0,
    fecha_atencion TIMESTAMP,
    CONSTRAINT fk_cola_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES paciente(id_paciente),
    CONSTRAINT chk_cola_estado CHECK (estado IN (
        'PENDIENTE', 'EN_PRECONSULTA', 'EN_CONSULTA',
        'EN_FARMACIA', 'FINALIZADO', 'CANCELADO'
    )),
    CONSTRAINT chk_cola_prioridad CHECK (prioridad >= 0)
);

CREATE INDEX idx_cola_estado ON cola_atencion(estado);
CREATE INDEX idx_cola_fecha_ingreso ON cola_atencion(fecha_ingreso);
CREATE INDEX idx_cola_paciente ON cola_atencion(id_paciente);


-- ==========================================================
-- 4. PERSONAL MÉDICO Y CONSULTAS
-- ==========================================================

CREATE TABLE medico (
    id_medico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    especialidad VARCHAR(100),
    telefono VARCHAR(20),
    correo VARCHAR(100),
    id_usuario BIGINT UNIQUE,
    CONSTRAINT fk_medico_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE TABLE consulta (
    id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_medico BIGINT NOT NULL,
    fecha_consulta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    motivo_consulta TEXT,
    historia_enfermedad_actual TEXT,
    impresion_clinica TEXT,
    plan_medico TEXT,
    precio_consulta DECIMAL(12,2) DEFAULT 0.00,
    CONSTRAINT fk_consulta_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES paciente(id_paciente),
    CONSTRAINT fk_consulta_medico
        FOREIGN KEY (id_medico)
        REFERENCES medico(id_medico)
);

CREATE INDEX idx_consulta_paciente ON consulta(id_paciente);
CREATE INDEX idx_consulta_medico ON consulta(id_medico);


-- ==========================================================
-- 5. VALORACIONES CLÍNICAS Y DIAGNÓSTICO
-- ==========================================================

CREATE TABLE signo_vital (
    id_signo_vital BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_consulta BIGINT,
    peso DECIMAL(5,2),
    talla DECIMAL(5,2),
    presion_arterial VARCHAR(20),
    glicemia DECIMAL(6,2),
    frecuencia_cardiaca INT,
    frecuencia_respiratoria INT,
    saturacion_oxigeno DECIMAL(5,2),
    temperatura DECIMAL(4,2),
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_signo_vital_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES paciente(id_paciente),
    CONSTRAINT fk_signo_vital_consulta
        FOREIGN KEY (id_consulta)
        REFERENCES consulta(id_consulta)
);

CREATE TABLE examen_fisico (
    id_examen_fisico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL UNIQUE,
    piel TEXT,
    conciencia TEXT,
    cardiopulmonar TEXT,
    abdomen TEXT,   
    soma TEXT,
    CONSTRAINT fk_examen_fisico_consulta
        FOREIGN KEY (id_consulta)
        REFERENCES consulta(id_consulta)
);

CREATE TABLE categoria_diagnostico (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE catalogo_cie10 (
    id_cie10 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(70) NOT NULL UNIQUE,
    descripcion VARCHAR(500) NOT NULL,
    id_categoria BIGINT,
    CONSTRAINT fk_catalogo_cie10_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria_diagnostico(id_categoria)
);

CREATE INDEX idx_cie10_codigo ON catalogo_cie10(codigo);
CREATE INDEX idx_catalogo_cie10_categoria ON catalogo_cie10(id_categoria);

CREATE TABLE diagnostico (
    id_diagnostico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL,
    id_categoria BIGINT,
    codigo_cie10 VARCHAR(70),
    descripcion TEXT NOT NULL,
    CONSTRAINT fk_diagnostico_consulta
        FOREIGN KEY (id_consulta)
        REFERENCES consulta(id_consulta),
    CONSTRAINT fk_diagnostico_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria_diagnostico(id_categoria)
);

CREATE INDEX idx_diagnostico_consulta ON diagnostico(id_consulta);
CREATE INDEX idx_diagnostico_categoria ON diagnostico(id_categoria);


-- ==========================================================
-- 6. CATÁLOGOS Y GESTIÓN DE FARMACIA
-- ==========================================================

CREATE TABLE categoria_medicamento (
    id_categoria_medicamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE casa_farmaceutica (
    id_casa_farmaceutica BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE parametro_farmacia (
    id_parametro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE medicamento (
    id_medicamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria_medicamento BIGINT,
    id_casa_farmaceutica BIGINT,
    nombre VARCHAR(150) NOT NULL,
    presentacion VARCHAR(100),
    concentracion VARCHAR(100),
    estado BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_medicamento_categoria
        FOREIGN KEY (id_categoria_medicamento)
        REFERENCES categoria_medicamento(id_categoria_medicamento),
    CONSTRAINT fk_medicamento_casa_farmaceutica
        FOREIGN KEY (id_casa_farmaceutica)
        REFERENCES casa_farmaceutica(id_casa_farmaceutica)
);

CREATE TABLE lote_medicamento (
    id_lote BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medicamento BIGINT NOT NULL,
    numero_lote VARCHAR(100),
    fecha_expiracion DATE NOT NULL,
    precio_unitario DECIMAL(12,2),
    cantidad_inicial INT DEFAULT 0,
    estado VARCHAR(30) DEFAULT 'ACTIVO',
    CONSTRAINT fk_lote_medicamento
        FOREIGN KEY (id_medicamento)
        REFERENCES medicamento(id_medicamento)
);

CREATE INDEX idx_lote_medicamento_medicamento ON lote_medicamento(id_medicamento);
CREATE INDEX idx_lote_medicamento_expiracion ON lote_medicamento(fecha_expiracion);


-- ==========================================================
-- 7. TRATAMIENTOS Y MOVIMIENTOS DE STOCK
-- ==========================================================

CREATE TABLE tratamiento (
    id_tratamiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL,
    observaciones TEXT,
    CONSTRAINT fk_tratamiento_consulta
        FOREIGN KEY (id_consulta)
        REFERENCES consulta(id_consulta)
);

CREATE INDEX idx_tratamiento_consulta ON tratamiento(id_consulta);

CREATE TABLE detalle_tratamiento (
    id_detalle_tratamiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tratamiento BIGINT NOT NULL,
    id_medicamento BIGINT NOT NULL,
    dosis VARCHAR(100),
    frecuencia VARCHAR(100),
    duracion VARCHAR(100),
    cantidad INT NOT NULL,
    CONSTRAINT fk_detalle_tratamiento_tratamiento
        FOREIGN KEY (id_tratamiento)
        REFERENCES tratamiento(id_tratamiento),
    CONSTRAINT fk_detalle_tratamiento_medicamento
        FOREIGN KEY (id_medicamento)
        REFERENCES medicamento(id_medicamento)
);

CREATE TABLE entrada_medicamento (
    id_entrada BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT,
    fecha_entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_entrada VARCHAR(50) NOT NULL,
    observaciones TEXT,
    CONSTRAINT fk_entrada_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE INDEX idx_entrada_fecha ON entrada_medicamento(fecha_entrada);

CREATE TABLE detalle_entrada_medicamento (
    id_detalle_entrada BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entrada BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(12,2),
    CONSTRAINT fk_detalle_entrada_entrada
        FOREIGN KEY (id_entrada)
        REFERENCES entrada_medicamento(id_entrada),
    CONSTRAINT fk_detalle_entrada_lote
        FOREIGN KEY (id_lote)
        REFERENCES lote_medicamento(id_lote)
);

CREATE TABLE salida_medicamento (
    id_salida BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT,
    id_usuario BIGINT,
    fecha_salida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_salida VARCHAR(50) NOT NULL,
    observaciones TEXT,
    CONSTRAINT fk_salida_consulta
        FOREIGN KEY (id_consulta)
        REFERENCES consulta(id_consulta),
    CONSTRAINT fk_salida_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);

CREATE INDEX idx_salida_fecha ON salida_medicamento(fecha_salida);
CREATE INDEX idx_salida_consulta ON salida_medicamento(id_consulta);

CREATE TABLE detalle_salida_medicamento (
    id_detalle_salida BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_salida BIGINT NOT NULL,
    id_lote BIGINT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(12,2) DEFAULT 0.00,
    CONSTRAINT fk_detalle_salida_salida
        FOREIGN KEY (id_salida)
        REFERENCES salida_medicamento(id_salida),
    CONSTRAINT fk_detalle_salida_lote
        FOREIGN KEY (id_lote)
        REFERENCES lote_medicamento(id_lote)
);


-- ==========================================================
-- 8. CIERRES DE INVENTARIO
-- ==========================================================

CREATE TABLE inventario_mensual (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_medicamento BIGINT NOT NULL,
    periodo_mes INT NOT NULL,
    periodo_anio INT NOT NULL,
    total_fisico_mes_anterior INT DEFAULT 0,
    pedidos INT DEFAULT 0,
    otras_entradas INT DEFAULT 0,
    total_fisico_mes INT DEFAULT 0,
    medicamento_vencido INT DEFAULT 0,
    total_entregado INT DEFAULT 0,
    saldo_actual INT DEFAULT 0,
    inventario_fisico INT DEFAULT 0,
    diferencia INT DEFAULT 0,
    precio_unitario DECIMAL(12,2),
    total_valor DECIMAL(14,2),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventario_medicamento
        FOREIGN KEY (id_medicamento)
        REFERENCES medicamento(id_medicamento),
    CONSTRAINT uq_inventario_mensual
        UNIQUE (id_medicamento, periodo_mes, periodo_anio)
);

CREATE INDEX idx_inventario_periodo ON inventario_mensual(periodo_anio, periodo_mes);

CREATE TABLE inventario_semanal (
    id_inventario_semanal BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT NOT NULL,
    numero_semana INT NOT NULL,
    cantidad_entregada INT DEFAULT 0,
    inventario_fisico INT DEFAULT 0,
    observaciones TEXT,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventario_semanal_inventario
        FOREIGN KEY (id_inventario)
        REFERENCES inventario_mensual(id_inventario),
    CONSTRAINT uq_inventario_semanal
        UNIQUE (id_inventario, numero_semana)
);

