-- ==========================================================
-- SCRIPT DE MIGRACIÓN: MÓDULO CLÍNICA Y CATÁLOGO CIE-10
-- ==========================================================

CREATE TABLE IF NOT EXISTS catalogo_cie10 (
    id_cie10       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR(20)  NOT NULL UNIQUE,
    descripcion    VARCHAR(500) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cie10_codigo ON catalogo_cie10(codigo);

INSERT INTO catalogo_cie10 (codigo, descripcion) VALUES
('J00', 'Rinofaringitis aguda (resfriado comun)'),
('J01', 'Sinusitis aguda'),
('J02', 'Faringitis aguda'),
('J03', 'Amigdalitis aguda'),
('I10', 'Hipertension esencial (primaria)'),
('E11', 'Diabetes mellitus tipo 2'),
('E10', 'Diabetes mellitus tipo 1'),
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso')
ON CONFLICT (codigo) DO NOTHING;
