-- Módulo de Farmacia: parámetros administrativos.
-- Las tablas maestras, lotes y entradas ya forman parte de dbv1.sql.

CREATE TABLE IF NOT EXISTS parametro_farmacia (
    id_parametro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255)
);

INSERT INTO parametro_farmacia (clave, valor, descripcion)
VALUES
    ('DIAS_ALERTA_VENCIMIENTO', '90', 'Días usados para alertas de vencimiento'),
    ('SISTEMA_DESPACHO_DEFAULT', 'FIFO', 'Método predeterminado de despacho')
ON CONFLICT (clave) DO NOTHING;
