ALTER TABLE paciente
    DROP COLUMN ocupacion,
    ADD COLUMN antecedentes_personales_patologicos TEXT,
    ADD COLUMN antecedentes_personales_familiares TEXT;


    sexo CHAR(1) NOT NULL
    CHECK (sexo IN ('M', 'F'))


    CREATE TABLE cola_atencion (
    id_cola BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_paciente BIGINT NOT NULL,

    fecha_ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',

    prioridad INT DEFAULT 0,

    fecha_atencion TIMESTAMP,

    CONSTRAINT fk_cola_atencion_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES paciente(id_paciente),

    CONSTRAINT chk_cola_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'EN_PRECONSULTA',
                'EN_CONSULTA',
                'EN_FARMACIA',
                'FINALIZADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT chk_cola_prioridad
        CHECK (prioridad >= 0)
);


CREATE INDEX idx_cola_estado
    ON cola_atencion(estado);

CREATE INDEX idx_cola_fecha_ingreso
    ON cola_atencion(fecha_ingreso);

CREATE INDEX idx_cola_paciente
    ON cola_atencion(id_paciente);
    