-- Migración del módulo de preconsulta para una base creada con dbv1.sql.
-- Ejecutar una sola vez en PostgreSQL antes de iniciar la aplicación.

ALTER TABLE paciente DROP COLUMN IF EXISTS ocupacion;
ALTER TABLE paciente ADD COLUMN IF NOT EXISTS antecedentes_personales_patologicos TEXT;
ALTER TABLE paciente ADD COLUMN IF NOT EXISTS antecedentes_personales_familiares TEXT;

CREATE TABLE IF NOT EXISTS cola_atencion (
    id_cola BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT NOT NULL REFERENCES paciente(id_paciente),
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    prioridad INT NOT NULL DEFAULT 0,
    fecha_atencion TIMESTAMP,
    CONSTRAINT chk_cola_estado CHECK (estado IN (
        'PENDIENTE', 'EN_PRECONSULTA', 'EN_CONSULTA',
        'EN_FARMACIA', 'FINALIZADO', 'CANCELADO'
    )),
    CONSTRAINT chk_cola_prioridad CHECK (prioridad >= 0)
);

CREATE INDEX IF NOT EXISTS idx_cola_estado ON cola_atencion(estado);
CREATE INDEX IF NOT EXISTS idx_cola_fecha_ingreso ON cola_atencion(fecha_ingreso);
CREATE INDEX IF NOT EXISTS idx_cola_paciente ON cola_atencion(id_paciente);

-- La versión inicial vinculaba los signos únicamente a consulta. Se conserva
-- esa relación para datos históricos y se añade el paciente para preconsulta.
ALTER TABLE signo_vital ADD COLUMN IF NOT EXISTS id_paciente BIGINT;
ALTER TABLE signo_vital ADD COLUMN IF NOT EXISTS fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE signo_vital ALTER COLUMN id_consulta DROP NOT NULL;

UPDATE signo_vital sv
SET id_paciente = c.id_paciente
FROM consulta c
WHERE sv.id_consulta = c.id_consulta
  AND sv.id_paciente IS NULL;

ALTER TABLE signo_vital ALTER COLUMN id_paciente SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_signo_vital_paciente'
    ) THEN
        ALTER TABLE signo_vital
            ADD CONSTRAINT fk_signo_vital_paciente
            FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente);
    END IF;
END $$;




ALTER TABLE diagnostico 
    ALTER COLUMN codigo_cie10 TYPE VARCHAR(70);


    CREATE TABLE categoria_diagnostico (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT
);

-- 1. Agregamos la columna de la llave foránea
ALTER TABLE diagnostico 
    ADD COLUMN id_categoria BIGINT;

-- 2. Creamos la relación entre tablas
ALTER TABLE diagnostico 
    ADD CONSTRAINT fk_diagnostico_categoria 
    FOREIGN KEY (id_categoria) 
    REFERENCES categoria_diagnostico(id_categoria);

-- 3. Creamos el índice para que las búsquedas por categoría sean rápidas
CREATE INDEX IF NOT EXISTS idx_diagnostico_categoria 
    ON diagnostico(id_categoria);

-- 4. Actualización para el catálogo de diagnósticos
ALTER TABLE catalogo_cie10 
    ALTER COLUMN codigo TYPE VARCHAR(70);

ALTER TABLE catalogo_cie10 
    ADD COLUMN IF NOT EXISTS id_categoria BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_catalogo_cie10_categoria'
    ) THEN
        ALTER TABLE catalogo_cie10
            ADD CONSTRAINT fk_catalogo_cie10_categoria
            FOREIGN KEY (id_categoria) REFERENCES categoria_diagnostico(id_categoria);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_catalogo_cie10_categoria 
    ON catalogo_cie10(id_categoria);