spring.application.name=hyma

spring.datasource.url=jdbc:postgresql://localhost:5432/hyma_db
spring.datasource.username=hyma_user
spring.datasource.password=hyma_pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# URL permitida para el Frontend (Por defecto usa localhost en desarrollo)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# ==========================================================
# CONFIGURACIÓN DE SEGURIDAD Y JWT
# ==========================================================
# Clave secreta para firmar tokens JWT (mínimo 256 bits / 32 bytes en Base64 o string seguro)
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Tiempo de expiración del token en milisegundos (24 horas = 86,400,000 ms)
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}