spring.application.name=hyma

spring.datasource.url=jdbc:postgresql://localhost:5432/hyma_db
spring.datasource.username=hyma_user
spring.datasource.password=hyma_pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true